services:
  - type: web
    name: student-lounge-bd-api
    env: node
    plan: free
    root: "."
    buildCommand: cd server; npm install
    startCommand: cd server; npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production