services:
  - type: web
    name: student-lounge-bd-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
